apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes lzdev.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
            max_concurrent 1000
            policy sequential
        }
        cache 30 {
            disable success lzdev.local
            disable denial lzdev.local
        }
        loop
        reload
        loadbalance
    }

    lucksafeysuser02.aa144.cn:53 {
        errors
        cache 30
        forward . 47.107.143.93 {
            prefer_udp
        }
    }

    hhjkkz.com:53 {
        errors
        cache 30
        forward . 47.107.143.93 {
            prefer_udp
        }
    }

    aa146.cn:53 {
        errors
        cache 30
        forward . 47.107.143.93 {
            prefer_udp
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-12T05:31:26Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "25084058"
  uid: 26f0f0c3-93c8-43ff-b5a2-98f42c6ed17d
